"$schema" = 'https://starship.rs/config-schema.json'

#include "all defined programming languages"
#include "all defined tools"
#include "all defined shells"
#include "all defined vcs"
#include "all defined environments"
format = """
[ ](blue)\
$os\
$username\
[](bg:sapphire fg:blue)\
$directory\
[](bg:green fg:sapphire)\
$git_branch\
$git_status\
[](fg:green bg:lavender)\
$c\
$rust\
$golang\
$php\
$java\
$kotlin\
$haskell\
$python\
$swift\
$elm\
$elixir\
$crystal\
$deno\
$dart\
$lua\
$zig\
$cpp\
$cmake\
$buf\
$deno\
$crystal\
$dart\
$elixir\
[](fg:lavender bg:teal)\
$conda\
$nodejs\
$react\
[](fg:teal bg:mauve)\
$time\
[ ](fg:mauve)\
$cmd_duration\
$character"""

palette = 'eldritch_darker'
# add_newline = true

[os]
disabled = false
style = "bg:blue fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Alpaquita = " "
AlmaLinux = " "
CachyOS = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
FreeBSD = " "
Garuda = "󰛓 "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Mabox = " "
Mariner = " "
MidnightBSD = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
Unknown = " "
Void = " "

[username]
show_always = true
style_user = "bg:blue fg:crust"
style_root = "bg:blue fg:crust"
format = '[ $user]($style)'

[directory]
read_only = " 󰌾"
style = "bg:sapphire fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:crust bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:crust bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:teal)]($style)'

[swift]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[lua]
symbol = ""
style = "bg:lavender"
format = '[[ $symbol( $version) ](fg:crust bg:lavender)]($style)'

[cpp]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:crust bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:teal"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:mauve"
format = '[[  $time ](fg:crust bg:mauve)]($style)'

# disable the line break, everything will be on one line
[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:lavender)'
vimcmd_replace_symbol = '[](bold fg:lavender)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:mauve"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.eldritch_default]
rosewater = "#f265b5"    # original magenta
flamingo = "#f16c75"     # original coral
pink = "#fd92ce"         # brighter pink variant
mauve = "#a48cf2"        # original purple
red = "#f9515d"          # original red
maroon = "#d4405a"       # darker red variant
peach = "#ffb347"        # warm orange (peach tone)
yellow = "#e9f941"       # original yellow
green = "#37f499"        # original green
teal = "#2dd4aa"         # green-teal hybrid
sky = "#04d1f9"          # original cyan
sapphire = "#66e4fd"     # lighter cyan variant
blue = "#9071f4"         # original blue
lavender = "#b794f6"     # lighter purple variant
text = "#ebfafa"         # original foreground
subtext1 = "#ffffff"     # pure white
subtext0 = "#7081d0"     # original muted blue
overlay2 = "#5a9c7a"     # muted green
overlay1 = "#c9d142"     # muted yellow-green
overlay0 = "#d666a3"     # muted pink
surface2 = "#2a2d40"     # slightly lighter than base
surface1 = "#252842"     # between surface2 and surface0
surface0 = "#21222c"     # original dark
base = "#212337"         # original background
mantle = "#1d1e2a"       # darker than base
crust = "#191a25"        # darkest

[palettes.eldritch_darker]
rosewater = "#cc4d99"    # darker magenta
flamingo = "#cc5860"     # darker coral
pink = "#d47ba8"         # darker pink variant
mauve = "#8b75d9"        # darker purple
red = "#d1424a"          # darker red
maroon = "#b33648"       # darkest red variant
peach = "#d4943d"        # darker warm orange
yellow = "#c4d136"       # darker yellow
green = "#2dcc82"        # darker green
teal = "#25a88a"         # darker green-teal
sky = "#0396b3"          # darker cyan
sapphire = "#52c7d9"     # darker light cyan
blue = "#7a5dd1"         # darker blue
lavender = "#9b7dd3"     # darker light purple
text = "#d8e6e6"         # darker foreground
subtext1 = "#c4d0d0"     # darker white
subtext0 = "#5c6ba6"     # darker muted blue
overlay2 = "#4a8066"     # darker muted green
overlay1 = "#a8b035"     # darker muted yellow-green
overlay0 = "#b85389"     # darker muted pink
surface2 = "#22243a"     # darker surface
surface1 = "#1f2138"     # darker between surfaces
surface0 = "#1a1b24"     # darker original dark
base = "#1a1b2e"         # darker background
mantle = "#171823"       # darker than base
crust = "#14151f"        # darkest

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[cmake]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_commit]
tag_symbol = '  '

[guix_shell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "